language: python
python:
  - "2.7"
  - "3.6"
dist: trusty
env:
  - DJANGO_SETTINGS_MODULE=settings.test PIP_USE_MIRRORS=true
before_install:
  - export PYTHONPATH="$HOME/build/gnosis/django-eth-events"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python django_eth_events/manage.py test && coverage run --source=django_eth_events django_eth_events/manage.py test
after_success:
  - coveralls
