language: python
cache: pip
python:
  - "3.6"
dist: trusty
env:
  global:
  - SOURCE_FOLDER=django_eth_events
  - PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=$SOURCE_FOLDER manage.py test --settings=config.settings.test
after_success:
  - coveralls
deploy:
  provider: script
  script: bash scripts/deploy.sh "${PYPI_USER}" "${PYPI_PASS}"
  skip_cleanup: true
  on:
    tags: true
